echo -e "\e[31m Hello in Red color\e[0m"
echo -e "\e[32m Hello in Green color\e[0m"
echo -e "\e[33m Hello in Yellow color\e[0m"
echo -e "\e[34m Hello in Blue color\e[0m"
echo -e "\e[35m Hello in Magenta color\e[0m"
echo -e "\e[36m Hello in cyan color\e[0m"
